"""Shared test fixtures.

Every test runs against a throwaway ``LECTERN_HOME``, so nothing touches the
developer's real config, sessions or logs.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

TESTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(TESTS_DIR))

FIXTURE_WAV = TESTS_DIR / "fixtures" / "lecture.wav"


@pytest.fixture(autouse=True)
def lectern_home(tmp_path, monkeypatch):
    """Redirect all Lectern paths into a temporary directory."""
    home = tmp_path / "lectern-home"
    home.mkdir()
    monkeypatch.setenv("LECTERN_HOME", str(home))
    monkeypatch.setenv("LECTERN_SKIP_WIZARD", "1")

    from lectern.sessions.index import fts5_available

    fts5_available.cache_clear()
    yield home


@pytest.fixture
def config():
    from lectern.config.models import LecternConfig

    return LecternConfig()


@pytest.fixture
def manager(config):
    """A ``SessionManager`` rooted in the temporary home."""
    from lectern.sessions.manager import SessionManager

    instance = SessionManager(config)
    yield instance
    instance.close()


@pytest.fixture
def fake_whisper():
    from fakes import FakeWhisperServer

    server = FakeWhisperServer().start()
    yield server
    server.stop()


@pytest.fixture
def fake_ollama():
    from fakes import FakeOllamaServer

    server = FakeOllamaServer().start()
    yield server
    server.stop()


@pytest.fixture
def fixture_wav() -> Path:
    if not FIXTURE_WAV.exists():  # pragma: no cover - generated by a script
        pytest.skip("run scripts/make_fixture_audio.py to generate the WAV fixture")
    return FIXTURE_WAV


@pytest.fixture
def sample_notes():
    """A small populated ``NoteState`` used by rendering and merge tests."""
    from lectern.notes.models import NoteItem, NoteState, TermEntry

    state = NoteState(current_topic="Cell Structure", summary="Bacterial cell structure.")
    state.add_topic("Cell Structure", timestamp=0.0)
    state.add_bullets(
        "key_points",
        [
            NoteItem(text="The membrane is a phospholipid bilayer.", timestamp=5.0),
            NoteItem(text="Gram-positive walls are thick.", starred=True, timestamp=30.0),
        ],
    )
    state.add_terms(
        "definitions",
        [TermEntry(term="Peptidoglycan", definition="Polymer in bacterial cell walls.")],
    )
    return state
